import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const libDir = path.join(__dirname, '../node_modules/typescript/lib');
const outputFile = path.join(__dirname, '../src/services/typescript/lib-bundle.ts');

// Read all lib.*.d.ts files
const files = fs.readdirSync(libDir).filter(f => f.startsWith('lib.') && f.endsWith('.d.ts'));

console.log(`Found ${files.length} lib files to bundle`);

// Generate the bundle
let output = `/* eslint-disable no-useless-escape */
/**
 * Generated TypeScript lib definitions bundled from node_modules/typescript/lib
 * This file is auto-generated by scripts/generate-lib-bundle.mjs
 * Do not edit manually
 */

export const libFiles: Record<string, string> = {
`;

for (const file of files) {
  const filePath = path.join(libDir, file);
  const content = fs.readFileSync(filePath, 'utf-8');

  // Escape backticks in content
  const escapedContent = content.replace(/`/g, '\\`').replace(/\$\{/g, '\\${');

  output += `  '/${file}': \`${escapedContent}\`,\n`;
}

output += `};\n`;

fs.writeFileSync(outputFile, output);
console.log(`Generated lib-bundle.ts (${(output.length / 1024).toFixed(2)} KB)`);
